### ISSUE TITLE
Please include the Quartical MIT license on casaNGI files that include the Autorestrictor plugin

### ISSUE THREAD

**Issue by sjperkins** [casangi/astrohack#172]
We've noticed that casaNGI has included a copy of the [Autorestrictor plugin](https://github.com/ratt-ru/QuartiCal/blob/fe1a23d96828b9eaa7200dff39cc5fe051b792a3/quartical/scheduling/__init__.py) from Quartical in the following location on astrohack
https://github.com/casangi/astrohack/blob/a17da1fa557ed5a6997a00bc5053036e6c714da8/src/astrohack/_utils/_dask_plugins/_astrohack_scheduler.py#L56-L182
We also note copies of the Autorestrictor exist in releases of [astroviper](https://pypi.org/project/astroviper) in the following locations:

- [astroviper 0.0.1](https://files.pythonhosted.org/packages/77/ea/82e95c4abdf89d2ba300443e493e2e5cc19404fa699d685d2e44efdd32e9/astroviper-0.0.1-py3-none-any.whl): viper/_concurrency/_dask_viper/_viper_scheduler.py
- [astroviper 0.0.5](https://files.pythonhosted.org/packages/70/ba/2effac77fa32a0e0ed598e3d13421b1324856c117abd2232c2dd031799b5/astroviper-0.0.5.tar.gz): src/astroviper/ _concurrency/_dask/_scheduler.py

RATT/RARG is very happy that our code is useful and is used in other software. We believe this fosters collaboration in a small field and we would like to see this continue.

We also believe that it is appropriate to include both attribution and the original license when including code written by others.
Could you please add attribution and the Quartical MIT license to the above, and any other locations that I may have missed?  A copy is available here:

https://github.com/ratt-ru/QuartiCal/blob/main/LICENSE

warm regards, Simon

**Comment by Jan-Willem** [comment]
Thank you for catching that @sjperkins. I have added the license.
