### ISSUE TITLE
Refactor variables called ant_id

### ISSUE THREAD

**Issue by vsmagalhaes** [casangi/astrohack#173]
Currently in the API the antenna selection parameter is called ant_id.
This requires that an extra step is taken when creating the local parameter dictionaries, as the antenna selection entry in the dictionaries has to be 'ant' to provide seamless integration with the file format in disk.

This ticket aims to rename all the instances of ant_id to ant and hence simplify the creation of local parameter dictionaries.

**Comment by jrhosk** [comment]
Yes, this. I wanted to fix this as it was frustrating. Victor coming out with the W.

**Comment by vsmagalhaes** [comment]
Your comment about it last week pushed me to doing it hahahaha
