### ISSUE TITLE
astrohack.dio.fix_pointing_table breaks if MS is not in current directory

### ISSUE THREAD

**Issue by Kitchi** [casangi/astrohack#188]
I have an older EVLA holography data set that needed the pointing table to be fixed. If I try running `fix_pointing_table` as (for example)

```
fix_pointing_table(ms_name = '../<holography_name>.ms', reference_antenna=['ea01', 'ea02'])
```
it fails with the following error : 

```
RuntimeError: Error in TaQL command: 'using style Python select NAME from ../THOL0001_sb31146700_1.57287.317363055554_HOLORASTER.timeavg.ms/ANTENNA'                                                               │
Error in select expression: :: or . is invalid in table name ../THOL0001_sb31146700_1.57287.317363055554_HOLORASTER.timeavg.ms/ANTENNA: no previous table available   
```

but if I move the MS into my current directory it works without issue. I suspect it might be because the path of the input MS is not properly sanitized when it is being ingested into the function.

**Comment by tnakazato** [comment]
I think enclosing table name with double quotes solves the problem. 

According to [TaQL documentation "3.5 FROM table_list"](https://casacore.github.io/casacore-notes/199.html#x1-220003.5),
> A persistent table can be used by giving its name which can contain path speciﬁcation and environment variables or the UNIX ~ notation. If the tablename contains a special character, the character can be escaped with a backslash or the table name can be enclosed in single or double quotes.
