### ISSUE TITLE
Create Mini Datasets and Automated Tests

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/astrohack#26]
- [x] Use CASA split function for the following datasets:
  - [x] ea25 before and after dataset:
      field='HOLORASTER'
      antenna='EA25&EA04, EA06&EA04',
      datacolumn='all',keepflags=True,
      spw=’1,15:4~60’,               //spw 1, 15  and channels 3 to 45.                   
  - [x] J1924-2914.ms.split.calibrated.SPW3 dataset:                              
      antenna='DA44&DV13', intent='MAP_ANTENNA_SURFACE#MIXED',
      datacolumn='all',keepflags=True

- [x] Apply fix_pointing_table to ea25 data
- [x] After doing a split the majority of the file size is due to the pointing table which does not get split out. Consequently, a function is needed that will split out the pointing table to only include the selected antennas. 
- [x] Upload these datasets to google drive and update the astrohack gdown functions.
- [x] Update stakeholder test and tutorial to make use of these datasets 
- [x] Write automated tests based on stakeholder tests (remove plotting).
  - [x] Modify extract_holog to return the holog_obs_dict and check it.
  - [x] Modify holog to return grid size and cell size and check it.
  - [x] Come up with a numerical check of results of extract_holog and holog (panel has this already in the stakeholder test and can be reused).

**Comment by jrhosk** [comment]
Fixed(?) the issue where the unit test was failing on github but no locally. For some reason the numbers returned are rounded differently on github versus locally. To make the test complete, I added `numpy.round(..., 7)` to each value being compared and the test passed. I don't think that this should be a long-term solution but it points to this being the issue to first order.
