### ISSUE TITLE
Table in a txt format (to be read in AIPS )

### ISSUE THREAD

**Issue by ppbbeaklini** [casangi/astrohack#30]
Allow user to export l m table with amplitude and phase in a txt file during extract_holog run.

- [ ] txt file should have the same layout as AIPS uses for holog input

- [ ] example at /lustre/aoc/sciops/pbeaklin/holography/casadev/EA27.MAR23I_02

- [ ] allow replacing l and m per EL and AZ

**Comment by vsmagalhaes** [comment]
Merged with issue #31 for compactness
