### ISSUE TITLE
AstroHACK Benchmarking Test Framework

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/astrohack#33]
Define the framework based on [airspeed-velocity](https://asv.readthedocs.io/en/stable/) to install and run benchmark performance tests of AstroHACK.

```[tasklist]
### Tasks
- [ ] pytest-benchmark plugin included in test dependencies and some subset added to the CI pipeline
- [x] airspeed-velocity added to the top level of the repository and some initial tests run
```

**Comment by smcastro** [comment]
@Jan-Willem, is the purpose of this ticket to start the implementation of the benchmarking tests? Or only a place holder for when the process is defined for the verification and validation?

**Comment by amcnicho** [comment]
We're proposing a framework that incorporates both [pytest-benchmark](https://pytest-benchmark.readthedocs.io/en/latest/) and [airspeed-velocity](https://asv.readthedocs.io/en/stable/index.html) to do performance testing of astroHACK. This will be elaborated on under the relevant section of [the wiki](https://github.com/casangi/astrohack/wiki/Test-Development#performance-tests).
