### ISSUE TITLE
Undesirable interaction between overwrite and reuse_point_zarr

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/astrohack#90]
When overwrite=True and reuse_point_zarr=True it will delete the point.zarr file and recalculate it. reuse_point_zarr should take precedence and the point.zarr should not be deleted. The previous holog.zarr should be deleted if overwrite=True. Also, reuse_point_zarr has no default listed in the docs.

overwrite=True and reuse_point_zarr=True also fails.

**Comment by Jan-Willem** [comment]
@jrhosk Can you please create a table that states the expected behavior for all combinations of overwrite and reuse_poinitng (FF, TF, TT, FT). This will be needed to update the documentation and create an appropriate set of tests.

**Comment by jrhosk** [comment]
Certainly
