### ISSUE TITLE
Write unit tests for astrohack_local_client()

### ISSUE THREAD

**Issue by smcastro** [casangi/astrohack#99]
Based on the user stories defined in https://github.com/casangi/astrohack/wiki/Test-Development#unit-tests: define here the test cases that will be implemented.

`class TestAstrohackClient():`
```[tasklist]
### Test Cases
- [x] test_client_spawned() --> the test case provided by Josh in this branch
- [x] test_client_with_valid_args() 
- [x] test_client_with_invalid_args()
- [x] test_client_with_log_to_file()
- [x] test_client_with_dask_dir()
```
I suggest the following to proceed with this branch: Akeem takes over the initial test script written by Josh (test_client.py) and add a few more test cases that we have discussed offline (as shown above). _test_client_with_log_to_file()_ should test when the user gives a specified name to save the log to disk. The test case should check that the log file is created. While testing that I have noticed that the client creates the logfile with the specified name, but adds a timestamp to it, therefore it is not easy to check the real name created. I think that should be clarified in the documentation of the API. 

Second thing I have noticed while running my local tests is that if a client is created in a test case, a later test case that creates another client will give a warning about the port already being used:

> github/astrohack/tests/unit/test_client.py::TestAstrohackClient::test_client_with_log_to_file
  /opt/scastro/miniconda3/envs/astrohack/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
  Perhaps you already have a cluster running?
  Hosting the HTTP server on port 50813 instead
    warnings.warn(

My questions:

- @jrhosk I'm wondering if there is a way to create another instance of the client using a different port? For example, can each test case before creating a client set this DEFAULT_DASK_ADDRESS="127.0.0.1:8786" using a different port?
- @awells-nrao , i think we could experiment with creating a self.client inside the setup and then calling a self.client.shutdown() in the teardown() to check if that gets rid of the warnings.
- @jrhosk , should we open issues for bugs that we find in the code and documentation?

..

**Comment by jrhosk** [comment]
Here is the code I use to verify the client has been spawned.

```
DEFAULT_DASK_ADDRESS="127.0.0.1:8786"

        logger = _get_astrohack_logger()

        if parallel:
            if not distributed.client._get_global_client():
                try:
                    distributed.Client(DEFAULT_DASK_ADDRESS, timeout=2)

                except Exception:
                    from astrohack.astrohack_client import astrohack_local_client

                    logger.info("local client not found, starting ...")

                    log_parms = {'log_level': 'DEBUG'}
                    client = astrohack_local_client(cores=2, memory_limit='8GB', log_parms=log_parms)
                    logger.info(client.dashboard_link)
```

**Comment by jrhosk** [comment]
> 
> @jrhosk I'm wondering if there is a way to create another instance of the client using a different port? For example, can > each test case before creating a client set this DEFAULT_DASK_ADDRESS="127.0.0.1:8786" using a different port?

That is what it does now. That is what is meant by "Hosting the HTTP server on port 50813 instead".

> @jrhosk , should we open issues for bugs that we find in the code and documentation?

I think so, yes.

**Comment by smcastro** [comment]
I see so the warning already assigns a new port to the new client.

**Comment by jrhosk** [comment]
> I see so the warning already assigns a new port to the new client.

Yes, the client just opens a new port if it finds a port is open. This is honestly not ideal in my opinion, you end up with a bunch of stale, open ports. I'm working on get ports better cleaned up after use.

I have already changed the test to close the opened ports after testing in each test case.

**Comment by jrhosk** [comment]
@smcastro Is there a test case for these?

- [ ] test_test_client_with_valid_args() 
- [ ] test_client_with_invalid_args()

I think all arguments should be valid. I would say there are three things to test here:
- client spawns correctly.
- `dask dir` created properly when specified.
- log file written correctly.

**Comment by jrhosk** [comment]
This is finished, making pull request.
